# Generated by Django 6.0.3 on 2026-03-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('challenges', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('author', 'challenge')},
        ),
    ]
