# Generated by Django 5.0.4 on 2026-03-15 20:20

import django.core.validators
import django.utils.timezone
import easy_meal_challenge.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_badge_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age must be higher then 7 years old', null=True, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cooking_exp',
            field=models.TextField(blank=True, help_text='Tell us a bit about your cooking experiences', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name can not be shorter than 3 letters or longer than 20 letters', max_length=20, validators=[easy_meal_challenge.accounts.validators.first_name_min_length_validator, easy_meal_challenge.accounts.validators.first_letter_upper_case]),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name can not be shorter than 2 letters or longer than 20 letters', max_length=20, null=True, validators=[django.core.validators.MaxLengthValidator(20), easy_meal_challenge.accounts.validators.last_name_min_length_validator, easy_meal_challenge.accounts.validators.first_letter_upper_case]),
        ),
    ]
